### ISSUE TITLE
Fails fetching https://www.diamond.co.jp

### ISSUE THREAD

**Issue by ysk24ok** [ysk24ok/jekyll-linkpreview#12]
```
  Liquid Exception: undefined method `[]' for nil:NilClass in /blog/_posts/2019-12-14-retrospect_2019.md
/var/lib/gems/2.3.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:54:in `extract_domain': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:13:in `get'
        from /var/lib/gems/2.3.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:113:in `get_properties'
        from /var/lib/gems/2.3.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:69:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:126:in `render_liquid'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:79:in `render_document'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
```

**Comment by sgitsp** [comment]
Same issue here with https://github.com

Liquid Exception: undefined method `[]' for nil:NilClass in /2009-01-01-markdown-basic.md
bundler: failed to load command: jekyll (/home/r00t/.rbenv/versions/2.6.1/bin/jekyll)
NoMethodError: undefined method `[]' for nil:NilClass
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:34:in `fetch'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:11:in `get'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:113:in `get_properties'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-linkpreview-0.2.0/lib/jekyll-linkpreview.rb:69:in `render'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:126:in `render_liquid'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:79:in `render_document'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/r00t/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /home/r00t/.rbenv/versions/2.6.1/bin/jekyll:23:in `load'
  /home/r00t/.rbenv/versions/2.6.1/bin/jekyll:23:in `<top (required)>'
