### ISSUE TITLE
link to #{domain} is broken

### ISSUE THREAD

**Issue by trombik** [ysk24ok/jekyll-linkpreview#26]
link to #{domain} in the default template is broken. 

https://github.com/ysk24ok/jekyll-linkpreview/blob/94597ecbbe26a9243ab6c04b138e1894d8a20e5d/lib/jekyll-linkpreview.rb#L256-L258

b6529d00abf13d9427a1a33b12b1c2216b5763dd fixed a bug in link to #{domain}. and d3d8d3698bf1de04a714884f1f009252324c1f29 removed "//" without reason.

**Comment by ysk24ok** [comment]
Thank you for reporting this problem @trombik . It's now fixed.
