### ISSUE TITLE
Access other og: properties

### ISSUE THREAD

**Issue by j-faria** [ysk24ok/jekyll-linkpreview#28]
This is an awesome plugin!
I was wondering if it's possible to access other properties, like `og:type` or `og:site_name` for example.

Ultimately, the plugin could make available *all* the meta tags starting with `og:`, or would that be too difficult?

**Comment by ysk24ok** [comment]
Thank you for the suggestion.
I think extracting all `og:` metadata is not difficult.
I'll try working on it in the near future.

**Comment by ysk24ok** [comment]
@j-faria Sorry for being so late. [v0.7.0](https://github.com/ysk24ok/jekyll-linkpreview/releases/tag/v0.7.0) has been released which includes other og properties access. Feel free to use it and let me know if you have any problems.
