### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by Clpsplug** [ysk24ok/jekyll-linkpreview#40]
I noticed this while fixing #38 via #39. 

## The issue

The CI is failing every time I push to GitHub.

It seems `jekyll-sass-converter` received a major update and its dependency `sass-embedded-1.57.1` has stopped supporting rubygems below 3.3.22, which is the default for the Docker image used for CI.

https://jekyllrb.com/news/2022/12/21/jekyll-sass-converter-3.0-released/  
https://github.com/jekyll/jekyll-sass-converter/blob/master/jekyll-sass-converter.gemspec#L19  
https://github.com/ntkme/sass-embedded-host-ruby/blob/5d751c76c57c5dd03620d48121c435863321d0b8/sass-embedded.gemspec#L25

## Potential fix
An update of rubygems seems to do the trick.

Since the CI crashes on me every time I push to my fork as I try to fix the other issues (and GitHub is spamming me with the 'failure' emails), I'm working on a fix and am about to submit a PR. 

I'm not sure if it is possible, though, since editing GitHub Actions usually requires a unique permission scope. If I am blocked b/c of security reasons, I'm afraid I have to ask you to do this. I can provide the patch.

**Comment by ysk24ok** [comment]
Broken CI was fixed by #43. Closing this issue.
