### ISSUE TITLE
Can I delete link in preview?

### ISSUE THREAD

**Issue by mmol93** [ysk24ok/jekyll-linkpreview#45]
I mean this part

![image](https://user-images.githubusercontent.com/69494230/217098747-2978c0d5-7e7c-49cd-8a82-6f68f6ae1eb3.png)

**Comment by ysk24ok** [comment]
@mmol93 Thank you for raising this issue.
I've deleted the link as other users raised similar issues. so with the next version of this plugin, you won't see the link.
In the meantime, you can use [a custom template](https://github.com/ysk24ok/jekyll-linkpreview#custom-templates) to disable the link.

**Comment by ysk24ok** [comment]
@mmol93 [v0.6.0](https://github.com/ysk24ok/jekyll-linkpreview/releases/tag/v0.6.0) which includes the change has been released. Feel free to try it out.

**Comment by mmol93** [comment]
@ysk24ok 
I confirmed!
Thanks a lot!!
