### ISSUE TITLE
`Dir.exists?` removed in Ruby 3.2.0

### ISSUE THREAD

**Issue by gaelsimon** [ysk24ok/jekyll-linkpreview#48]
Starting in Ruby 3.2.0 the `exists?` (pluralized) alias for `exist?` has been removed.
It is required to use the singular-form `exist?`

**Comment by ysk24ok** [comment]
@gaelsimon Thank you for reporting this issue which I've just fixed. Please wait some time for the next version to be released.

**Comment by ysk24ok** [comment]
@gaelsimon [v0.7.0](https://github.com/ysk24ok/jekyll-linkpreview/releases/tag/v0.7.0) has been released. Feel free to use it and let me know if you have any problems.
